### PR TITLE
Errorhandlingissues

### PR DESCRIPTION
**Pull request by rb50**
- completed issues as per week 5 epic:

- Added an edge case to the tests where we try to sum elements and the first one is NaN and the second one is a number (Relates to #32) (t.throws(() => sumArray(['', 2]), TypeError, 'Calling sumArray with ([\'\', 2]) should throw a new TypeError');

- Reordered the approaches so that callbacks are introduced first (approach 1) followed by throwing an error (approach 2) followed by returning an error (approach 3) 

- Improved explanations where necessary

- It looks as though there are a lot of changes- because the approaches have now been reordered and so files have moved around and been renamed, however there are not too many actual changes to the code.

### CODE REVIEW

**Comment by rb50** [comment]
@eliascodes Thanks for your feedback! 😄 Re: approach 3, I've just tried running it with the solutions and the tests are all passing. Could you let me know what error message you're getting when you try to do the same? Thanks! ✨

**Comment by njseeto** [comment]
Hey Becky! I've just run the tests with the solutions. The only one that is failing for me is approach 3; wrapErrorCheck. 
screen shot 2018-03-05 at 09 02 38
😊

**Comment by rb50** [comment]
@njseeto thanks! I see what's happened. I was copying each solution in, not the whole file 🙃. Will sort!

**Comment by rb50** [comment]
@eliascodes can this be merged? Let me know if there are any more changes needed 😄

**Comment by eliascodes** [comment]
@rb50 Sorry, yes. You took the single-line thing a bit further than I had intended, but no worries 😆. Thanks for your changes 👍

**Pull request merged**
